### ISSUE TITLE
Callback not called if file is smalle than 262 bytes

### ISSUE THREAD

**Issue by Ajnasz** [binded/file-type-stream#1]
Callback should be called at least with `null` value if the file is too small to have enough magic bytes.

**Comment by wesbaker** [comment]
@Ajnasz I needed something like what you're doing in a project and I got around it by using a `finish` event:

```js
const streamPassThrough = new PassThrough();

try {
  const result = await new Promise((resolve, reject) => {
    stream
      .pipe(fileTypeStream(resolve))
      .pipe(streamPassThrough)
      .on('finish', reject.bind(null, 'Could not read enough of file to get mimetype'));
  });

  stream = streamPassThrough;

  return result;
} catch (err) {
  return { ext: undefined, mime: undefined };
}
```

The key is that the `Promise` should `resolve` before finishing if the file is big enough, but it'll `finish` before it `resolves` if `fileTypeStream` can't get enough bytes.
